export const CHANGE_GRID_SIZE = "CHANGE_GRID_SIZE";
export const SET_VOICE = "SET_VOICE";
export const CHANGE_GRID = "CHANGE_GRID";
export const CHANGE_OUTPUT_FIELD = "CHANGE_OUTPUT_FIELD";
export const ADD_ELEMENT_TO_OUTPUT_FIELD = "ADD_ELEMENT_TO_OUTPUT_FIELD";
export const CLEAR_OUTPUT_FIELD = "CLEAR_OUTPUT_FIELD";
export const DELETE_OUTPUT_ELEMENT = "DELETE_OUTPUT_ELEMENT";
